name: nocturnal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^4.3.0
  lottie: ^3.1.3
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/Animations/owl_waving.json
    - lib/Animations/heresNothingOwl.json
    - lib/Animations/login_owl.json
    - lib/Images/1.jpg
    - lib/Images/2.jpg
    - lib/Images/3.jpg
    - lib/Images/4.jpg
    - lib/Images/5.jpg
    - lib/Images/6.jpg
    - lib/Images/7.jpg
    - lib/Images/8.jpg
    - lib/Images/9.jpg
    - lib/Images/10.jpg
    - lib/Images/11.jpg
    - lib/Images/12.jpg
    - lib/Images/13.jpg